import { STORE } from "./catalog";
import type { Audience, Campaign } from "./types";

function dayStamp(offset: number) {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() - offset);
  return d.toISOString().slice(0, 10);
}

const aud = (
  id: string,
  name: string,
  description: string,
  size: string,
  affinity: number,
  tags: string[],
): Audience => ({ id, name, description, size, affinity, tags });

const HOUSE = STORE.name;
const DEST = STORE.href;

export function seedCampaigns(): Campaign[] {
  return [
    {
      id: "c_deepwork",
      name: "Deep Work Pack — founder mornings",
      brand: HOUSE,
      product: "Deep Work Prompt Pack · 120 prompts, PDF + Notion",
      status: "active",
      objective: "conversions",
      platforms: ["search", "social"],
      dailyBudget: 180,
      cpcBid: 1.45,
      destination: DEST,
      owned: true,
      aov: 19,
      strategy:
        "Own ‘deep work prompt’ and ‘focus block AI’ queries. Social is a spec, not a lifestyle: 120 prompts, PDF + Notion, watch it run free. Retarget catalog browsers with the 3+ bundle.",
      targeting:
        "Solo founders and operators, 25–45, high Notion/ChatGPT usage. Exclude students and prompt-freebie hunters.",
      createdAt: dayStamp(18),
      creatives: [
        {
          id: "cr_dw_search",
          format: "search",
          headline: "Deep Work Prompt Pack — 120 Prompts",
          subhead: STORE.host,
          body: "Prioritization, focus blocks, end-of-day reset. PDF + Notion. $19 one-time. Watch it run on your own task first.",
          cta: "Watch it run",
        },
        {
          id: "cr_dw_social",
          format: "social",
          headline: "120 prompts. One focus block.",
          subhead: "Deep Work Prompt Pack",
          body: "Not a course. A spec: prioritization, deep work, a Friday reset. Load it in Claude, ChatGPT, or Gemini. $19.",
          cta: "Get the pack",
        },
        {
          id: "cr_dw_disp",
          format: "display",
          headline: "A spec for the first ninety minutes.",
          subhead: "Deep Work Prompt Pack",
          body: "120 prompts. PDF + Notion. $19 one-time on multinicheai.com.",
          cta: "Open the catalog",
        },
      ],
      audiences: [
        aud("a_dw_1", "Solo founders on Notion", "Founders using Notion weekly; follows productivity and operator accounts.", "2.4M", 91, ["founders", "notion", "ops"]),
        aud("a_dw_2", "ChatGPT power users", "Heavy generative-AI usage, not first-week trialists.", "8.1M", 78, ["chatgpt", "productivity"]),
      ],
      stats: [],
    },
    {
      id: "c_inbox",
      name: "Inbox Zero — sales & CS",
      brand: HOUSE,
      product: "Inbox Zero Automation · Make.com blueprint",
      status: "active",
      objective: "conversions",
      platforms: ["search", "social"],
      dailyBudget: 220,
      cpcBid: 1.62,
      destination: DEST,
      owned: true,
      aov: 29,
      strategy:
        "High-intent ‘inbox automation’ and ‘AI email triage’ search. Creative is the blueprint: auto-sort, draft, flag humans. Proof page before checkout.",
      targeting:
        "Sales and CS leads at 5–50 person companies. Make.com and Zapier users. Exclude consumer Gmail-cleanup apps.",
      createdAt: dayStamp(14),
      creatives: [
        {
          id: "cr_in_search",
          format: "search",
          headline: "Inbox Zero Automation — Make.com",
          subhead: STORE.host,
          body: "Sorts, drafts, flags what needs a person. Blueprint, not a seat. $29 one-time. See the live proof.",
          cta: "See the proof",
        },
        {
          id: "cr_in_social",
          format: "social",
          headline: "The inbox sorts itself. You take the exceptions.",
          subhead: "Inbox Zero Automation",
          body: "A Make.com blueprint that drafts replies and leaves the human ones alone. $29. Watch it run on a real thread first.",
          cta: "Open the catalog",
        },
        {
          id: "cr_in_disp",
          format: "display",
          headline: "Draft the 58. Open the 12.",
          subhead: "Inbox Zero Automation",
          body: "Make.com blueprint. $29 one-time. multinicheai.com",
          cta: "See the proof",
        },
      ],
      audiences: [
        aud("a_in_1", "Sales ops on Make.com", "Revops and CS managers with Make or Zapier in the stack.", "1.6M", 88, ["sales", "make", "cs"]),
      ],
      stats: [],
    },
    {
      id: "c_calendar",
      name: "Content Calendar Autopilot",
      brand: HOUSE,
      product: "Content Calendar Autopilot · Zapier blueprint",
      status: "active",
      objective: "traffic",
      platforms: ["social", "display"],
      dailyBudget: 260,
      cpcBid: 1.12,
      destination: DEST,
      owned: true,
      aov: 24,
      strategy:
        "Prospecting on marketing-tool inventory. Frequency cap 3/week. The line is the spec: notes in, queued posts out. Send to catalog, then bundle.",
      targeting:
        "Marketers shipping weekly content, solopreneurs and 2–10 person studios. Exclude enterprise marketing-cloud buyers.",
      createdAt: dayStamp(22),
      creatives: [
        {
          id: "cr_cc_social",
          format: "social",
          headline: "Notes in. Posts queued.",
          subhead: "Content Calendar Autopilot",
          body: "A Zapier blueprint that drafts from your notes and lines them up by channel. $24 one-time. 15% off three tools.",
          cta: "Watch it draft",
        },
        {
          id: "cr_cc_disp",
          format: "display",
          headline: "A calendar that writes back.",
          subhead: "Multiniche AI",
          body: "Zapier blueprint. $24. Built once, sold as an instrument.",
          cta: "Open the catalog",
        },
      ],
      audiences: [
        aud("a_cc_1", "Solopreneur marketers", "Creators and marketers posting 3+ times a week across two channels.", "5.2M", 84, ["marketing", "zapier", "content"]),
        aud("a_cc_2", "Small studio operators", "2–10 person agencies running content for clients.", "1.1M", 76, ["agency", "content"]),
      ],
      stats: [],
    },
    {
      id: "c_studio",
      name: "Agent Studio — first run free",
      brand: HOUSE,
      product: "Claude Agent Studio · prepaid credits from $9",
      status: "active",
      objective: "leads",
      platforms: ["search", "display"],
      dailyBudget: 340,
      cpcBid: 2.15,
      destination: DEST,
      owned: true,
      aov: 9,
      strategy:
        "Capture ‘Claude agent’ and ‘custom GPT for work’ intent. Lead with first run free and credits that never expire. Display only on AI-tool and founder inventory, tight frequency.",
      targeting:
        "Operators who already pay for Claude or ChatGPT. Founders needing investor updates, pricing notes, migration plans. Exclude hobby prompt collectors.",
      createdAt: dayStamp(9),
      creatives: [
        {
          id: "cr_st_search",
          format: "search",
          headline: "Rent a Claude Agent — First Run Free",
          subhead: STORE.host,
          body: "Investor update, pricing analysis, migration plan. 1 credit per quick run. Credits from $9, never expire.",
          cta: "Start a free run",
        },
        {
          id: "cr_st_disp",
          format: "display",
          headline: "A Claude agent. One task. Then stop.",
          subhead: "Agent Studio",
          body: "No seat. Prepaid credits. First run free on multinicheai.com.",
          cta: "Run it once",
        },
      ],
      audiences: [
        aud("a_st_1", "Claude subscribers", "Active Claude or ChatGPT Plus users with work, not school, intent.", "3.8M", 93, ["claude", "operators"]),
        aud("a_st_2", "Pre-seed to Series A founders", "Recently incorporated, fundraising or pricing pages in-market.", "890K", 81, ["founders", "fundraising"]),
      ],
      stats: [],
    },
    {
      id: "c_digest",
      name: "Code Review Digest — paused",
      brand: HOUSE,
      product: "Code Review Digest · GitHub Actions blueprint",
      status: "paused",
      objective: "traffic",
      platforms: ["search"],
      dailyBudget: 140,
      cpcBid: 1.55,
      destination: DEST,
      owned: true,
      aov: 26,
      strategy:
        "Branded + ‘PR digest GitHub Action’ terms only while we rebuild the proof. Keep a floor on exact-match; cut broad until the demo is live again.",
      targeting: "Engineering managers and staff engineers on GitHub. Exclude bootcamp and student queries.",
      createdAt: dayStamp(30),
      creatives: [
        {
          id: "cr_cd_search",
          format: "search",
          headline: "PR Digest with Risk Flags — GitHub Action",
          subhead: STORE.host,
          body: "Daily summary of open PRs. Risk flags, not noise. $26 one-time blueprint.",
          cta: "See the blueprint",
        },
        {
          id: "cr_cd_disp",
          format: "display",
          headline: "The PR that sat for nine days.",
          subhead: "Code Review Digest",
          body: "GitHub Action. Risk flags, not a feed. $26 on multinicheai.com.",
          cta: "See the blueprint",
        },
      ],
      audiences: [
        aud("a_cd_1", "Eng managers on GitHub", "Engineering leads at 10–200 person product companies.", "720K", 90, ["github", "engineering"]),
      ],
      stats: [],
    },
    {
      id: "c_relm",
      name: "Relm — operator prompt stacks",
      brand: "Relm",
      product: "Relm Operator Library",
      status: "active",
      objective: "traffic",
      platforms: ["search", "social"],
      dailyBudget: 210,
      cpcBid: 1.38,
      destination: "https://example.com",
      owned: false,
      aov: 29,
      strategy: "Compete on productivity and founder queries with a library angle.",
      targeting: "Founders, Notion users, ChatGPT power users looking for prompt stacks.",
      createdAt: dayStamp(11),
      creatives: [
        {
          id: "cr_relm_s",
          format: "search",
          headline: "Relm Operator Library — Prompt Stacks",
          subhead: "relm.co",
          body: "Stacks for the morning block, the Friday reset, and the board update. Built for operators.",
          cta: "Browse stacks",
        },
        {
          id: "cr_relm_so",
          format: "social",
          headline: "A library, not a course.",
          subhead: "Relm",
          body: "Operator prompt stacks. Load them in the model you already pay for.",
          cta: "Open Relm",
        },
        {
          id: "cr_relm_d",
          format: "display",
          headline: "Prompts with a table of contents.",
          subhead: "Relm",
          body: "The operator library.",
          cta: "Browse",
        },
      ],
      audiences: [
        aud("a_relm_1", "Founder prompt buyers", "In-market for productivity prompts.", "3.1M", 74, ["founders", "productivity", "chatgpt"]),
      ],
      stats: [],
    },
    {
      id: "c_north",
      name: "Northbound — Claude for the company",
      brand: "Northbound",
      product: "Northbound Claude desk",
      status: "active",
      objective: "leads",
      platforms: ["search", "display"],
      dailyBudget: 400,
      cpcBid: 2.05,
      destination: "https://example.com",
      owned: false,
      aov: 49,
      strategy: "Bid on Claude agent and founder-ops queries. Seat-based, so they overpay on CPC.",
      targeting: "Founders and operators already paying for Claude.",
      createdAt: dayStamp(6),
      creatives: [
        {
          id: "cr_nb_s",
          format: "search",
          headline: "Claude, wired to the company",
          subhead: "northbound.io",
          body: "Investor updates, pricing notes, migration plans. A desk, not a chatbot.",
          cta: "Book a walkthrough",
        },
        {
          id: "cr_nb_d",
          format: "display",
          headline: "Stop pasting the company into chat.",
          subhead: "Northbound",
          body: "Claude with your files attached. For founders.",
          cta: "See the desk",
        },
      ],
      audiences: [
        aud("a_nb_1", "Claude subscribers", "Work intent, paid seats.", "2.2M", 88, ["claude", "founders", "operators"]),
      ],
      stats: [],
    },
    {
      id: "c_stack",
      name: "Stackline — inbox kits",
      brand: "Stackline",
      product: "Stackline Inbox Kit",
      status: "active",
      objective: "conversions",
      platforms: ["search", "social"],
      dailyBudget: 190,
      cpcBid: 1.58,
      destination: "https://example.com",
      owned: false,
      aov: 39,
      strategy: "Own Make.com and inbox-triage adjacency. Recurring kit, slightly higher bid.",
      targeting: "Sales and CS on Make.com and Zapier.",
      createdAt: dayStamp(8),
      creatives: [
        {
          id: "cr_stkl_s",
          format: "search",
          headline: "Inbox Kit for Make.com Teams",
          subhead: "stackline.app",
          body: "Triage, draft, escalate. A kit your CS lead can run this afternoon.",
          cta: "Get the kit",
        },
        {
          id: "cr_stkl_so",
          format: "social",
          headline: "Exceptions only.",
          subhead: "Stackline",
          body: "The rest of the inbox is a scenario. Sales and CS, Make.com.",
          cta: "See the kit",
        },
        {
          id: "cr_stkl_d",
          format: "display",
          headline: "Triage is a scenario.",
          subhead: "Stackline Inbox Kit",
          body: "Make.com. Sales and CS.",
          cta: "Get the kit",
        },
      ],
      audiences: [
        aud("a_stk_1", "Revops on Make", "CS and sales ops.", "1.4M", 82, ["sales", "make", "cs", "zapier"]),
      ],
      stats: [],
    },
    {
      id: "c_quill",
      name: "Quillroom — editorial calendar",
      brand: "Quillroom",
      product: "Quillroom Calendar",
      status: "active",
      objective: "traffic",
      platforms: ["social", "display"],
      dailyBudget: 175,
      cpcBid: 0.98,
      destination: "https://example.com",
      owned: false,
      aov: 22,
      strategy: "Cheap display on writer and marketing inventory. Volume game.",
      targeting: "Writers, marketers, small agencies shipping weekly content.",
      createdAt: dayStamp(16),
      creatives: [
        {
          id: "cr_q_so",
          format: "social",
          headline: "The calendar that keeps the voice.",
          subhead: "Quillroom",
          body: "Draft from notes. Queue by channel. Lock the voice so it still sounds like you.",
          cta: "Try Quillroom",
        },
        {
          id: "cr_q_d",
          format: "display",
          headline: "Editorial, not a mood board.",
          subhead: "Quillroom",
          body: "Calendars for writers and small studios.",
          cta: "Open",
        },
      ],
      audiences: [
        aud("a_q_1", "Weekly publishers", "Marketers and writers posting 3× a week.", "4.4M", 71, ["marketing", "content", "writers", "agency"]),
      ],
      stats: [],
    },
  ];
}
