import { createFileRoute } from "@tanstack/react-router";
import { withCors } from "@/lib/ads-http";

// Built with concatenation so HTML-entity decoding cannot corrupt the served JS.
const TAG = [
  "(() => {",
  "  function originOf() {",
  '    var s = document.currentScript || document.querySelector(\'script[src*="tag.js"]\');',
  "    if (s && s.src) {",
  "      try { return new URL(s.src).origin; } catch (e) {}",
  "    }",
  "    return location.origin;",
  "  }",
  "  var ORIGIN = originOf();",
  "",
  "  function qs(el) {",
  "    var p = new URLSearchParams();",
  '    p.set("site", el.getAttribute("data-site") || location.hostname);',
  '    p.set("slot", el.getAttribute("data-slot") || "s_web_display");',
  '    p.set("format", el.getAttribute("data-format") || "display");',
  '    p.set("pageview", "pv_" + Math.random().toString(36).slice(2, 10) + Date.now().toString(36));',
  '    p.set("url", location.href);',
  '    var tags = el.getAttribute("data-tags");',
  '    if (tags) p.set("tags", tags);',
  '    var q = el.getAttribute("data-q") || (new URLSearchParams(location.search).get("q") || "");',
  '    if (q) p.set("q", q);',
  "    return p.toString();",
  "  }",
  "",
  "  function escapeHtml(s) {",
  '    return String(s || "").replace(/[&<>"\'\\/]/g, function (c) {',
  '      if (c === "&") return "&" + "amp;";',
  '      if (c === "<") return "&" + "lt;";',
  '      if (c === ">") return "&" + "gt;";',
  '      if (c === \'"\') return "&" + "quot;";',
  '      if (c === "/") return "&" + "#47;";',
  '      return "&" + "#39;";',
  "    });",
  "  }",
  "",
  "  function remnant(el) {",
  '    el.innerHTML = \'<div style="font:12px/1.4 ui-sans-serif,system-ui,sans-serif;border:1px dashed #d7d2c8;padding:12px 14px;color:#6b6560;background:#faf8f4">Unsold slot · <a href="\' + ORIGIN + \'/create" style="color:#111">Advertise on Multiniche Ads</a></div>\';',
  "  }",
  "",
  "  function unit(ad) {",
  '    var host = ad.host || (ad.owned ? "multinicheai.com" : "Sponsored");',
  "    var img = ad.imageUrl",
  '      ? \'<img src="\' + escapeHtml(ad.imageUrl) + \'" alt="" style="width:100%;height:auto;display:block;max-height:180px;object-fit:cover"/>\'',
  '      : "";',
  '    if (ad.format === "search") {',
  "      return '<div style=\"font:14px/1.45 ui-sans-serif,system-ui,sans-serif;border:1px solid #e6e1d6;padding:12px 14px;background:#fff;color:#1a1916\">'",
  '        + \'<div style="font-size:11px;color:#6b6560">Sponsored · \' + escapeHtml(host) + "</div>"',
  '        + \'<div style="margin-top:4px;font-weight:600;color:#1a1916">\' + escapeHtml(ad.headline) + "</div>"',
  '        + \'<div style="margin-top:4px;color:#4a4640;font-size:13px">\' + escapeHtml(ad.body) + "</div>"',
  '        + \'<div style="margin-top:8px;font-size:12px;color:#6b6560">\' + escapeHtml(ad.cta) + " →</div></div>";',
  "    }",
  "    return '<div style=\"font:14px/1.45 ui-sans-serif,system-ui,sans-serif;border:1px solid #e6e1d6;overflow:hidden;background:#fff;color:#1a1916\">'",
  '      + \'<div style="display:flex;justify-content:space-between;align-items:center;padding:8px 12px;font-size:11px;color:#6b6560;letter-spacing:.12em;text-transform:uppercase">\'',
  '      + "<span>" + escapeHtml(ad.brand || "Sponsored") + "</span><span>Ads · Multiniche</span></div>"',
  "      + img",
  '      + (img ? "" : \'<div style="padding:16px 14px 8px;font-family:Georgia,ui-serif,serif;font-size:20px;line-height:1.2">\' + escapeHtml(ad.headline) + "</div>")',
  '      + \'<div style="padding:10px 14px 14px">\' + (img ? \'<div style="font-weight:600">\' + escapeHtml(ad.headline) + "</div>" : "")',
  '      + \'<div style="margin-top:4px;color:#4a4640;font-size:13px">\' + escapeHtml(ad.body) + "</div>"',
  '      + \'<div style="margin-top:10px;display:inline-block;background:#111;color:#fff;padding:8px 12px;font-size:12px">\' + escapeHtml(ad.cta) + "</div></div></div>";',
  "  }",
  "",
  "  function fill(el) {",
  '    if (el.getAttribute("data-mn-filled")) return;',
  '    el.setAttribute("data-mn-filled", "pending");',
  '    fetch(ORIGIN + "/api/ads/serve?" + qs(el), { credentials: "omit" })',
  "      .then(function (r) { return r.json(); })",
  "      .then(function (ad) {",
  '        el.setAttribute("data-mn-filled", ad && ad.fill ? "1" : "0");',
  "        if (!ad || !ad.fill) { remnant(el); return; }",
  "        el.innerHTML = '<a href=\"' + escapeHtml(ad.clickUrl) + '\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"display:block;text-decoration:none;color:inherit\">' + unit(ad) + '</a>';",
  "      })",
  "      .catch(function () {",
  '        el.setAttribute("data-mn-filled", "0");',
  "        remnant(el);",
  "      });",
  "  }",
  "",
  "  function run() {",
  '    var nodes = document.querySelectorAll("[data-mn-ad]");',
  "    for (var i = 0; i < nodes.length; i++) fill(nodes[i]);",
  "  }",
  "",
  "  function boot() {",
  "    run();",
  "    if (window.__mnAdObs) return;",
  "    var obs = new MutationObserver(function () { run(); });",
  "    obs.observe(document.documentElement, { childList: true, subtree: true });",
  "    window.__mnAdObs = obs;",
  "  }",
  "",
  '  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);',
  "  else boot();",
  "})();",
].join("\n");

export const Route = createFileRoute("/tag.js")({
  server: {
    handlers: {
      GET: async () =>
        withCors(
          new Response(TAG, {
            status: 200,
            headers: {
              "Content-Type": "application/javascript; charset=utf-8",
              "Cache-Control": "no-store",
            },
          }),
        ),
    },
  },
});
