/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudiencesRouteImport } from './routes/audiences'
import { Route as CreateRouteImport } from './routes/create'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TagDotjsRouteImport } from './routes/tag[.]js'
import { Route as WebRouteImport } from './routes/web'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ApiAdsClickRouteImport } from './routes/api/ads/click'
import { Route as ApiAdsOfferRouteImport } from './routes/api/ads/offer'
import { Route as ApiAdsRunRouteImport } from './routes/api/ads/run'
import { Route as ApiAdsServeRouteImport } from './routes/api/ads/serve'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiencesRoute = AudiencesRouteImport.update({
  id: '/audiences',
  path: '/audiences',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TagDotjsRoute = TagDotjsRouteImport.update({
  id: '/tag.js',
  path: '/tag.js',
  getParentRoute: () => rootRouteImport,
} as any)
const WebRoute = WebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsClickRoute = ApiAdsClickRouteImport.update({
  id: '/api/ads/click',
  path: '/api/ads/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsOfferRoute = ApiAdsOfferRouteImport.update({
  id: '/api/ads/offer',
  path: '/api/ads/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsRunRoute = ApiAdsRunRouteImport.update({
  id: '/api/ads/run',
  path: '/api/ads/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsServeRoute = ApiAdsServeRouteImport.update({
  id: '/api/ads/serve',
  path: '/api/ads/serve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiences': typeof AudiencesRoute
  '/create': typeof CreateRoute
  '/inventory': typeof InventoryRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/tag.js': typeof TagDotjsRoute
  '/web': typeof WebRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/p/$slug': typeof PSlugRoute
  '/api/ads/click': typeof ApiAdsClickRoute
  '/api/ads/offer': typeof ApiAdsOfferRoute
  '/api/ads/run': typeof ApiAdsRunRoute
  '/api/ads/serve': typeof ApiAdsServeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiences': typeof AudiencesRoute
  '/create': typeof CreateRoute
  '/inventory': typeof InventoryRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/tag.js': typeof TagDotjsRoute
  '/web': typeof WebRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/p/$slug': typeof PSlugRoute
  '/api/ads/click': typeof ApiAdsClickRoute
  '/api/ads/offer': typeof ApiAdsOfferRoute
  '/api/ads/run': typeof ApiAdsRunRoute
  '/api/ads/serve': typeof ApiAdsServeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiences': typeof AudiencesRoute
  '/create': typeof CreateRoute
  '/inventory': typeof InventoryRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/tag.js': typeof TagDotjsRoute
  '/web': typeof WebRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/p/$slug': typeof PSlugRoute
  '/api/ads/click': typeof ApiAdsClickRoute
  '/api/ads/offer': typeof ApiAdsOfferRoute
  '/api/ads/run': typeof ApiAdsRunRoute
  '/api/ads/serve': typeof ApiAdsServeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audiences'
    | '/create'
    | '/inventory'
    | '/llms.txt'
    | '/search'
    | '/studio'
    | '/tag.js'
    | '/web'
    | '/campaigns/$id'
    | '/p/$slug'
    | '/api/ads/click'
    | '/api/ads/offer'
    | '/api/ads/run'
    | '/api/ads/serve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiences'
    | '/create'
    | '/inventory'
    | '/llms.txt'
    | '/search'
    | '/studio'
    | '/tag.js'
    | '/web'
    | '/campaigns/$id'
    | '/p/$slug'
    | '/api/ads/click'
    | '/api/ads/offer'
    | '/api/ads/run'
    | '/api/ads/serve'
  id:
    | '__root__'
    | '/'
    | '/audiences'
    | '/create'
    | '/inventory'
    | '/llms.txt'
    | '/search'
    | '/studio'
    | '/tag.js'
    | '/web'
    | '/campaigns/$id'
    | '/p/$slug'
    | '/api/ads/click'
    | '/api/ads/offer'
    | '/api/ads/run'
    | '/api/ads/serve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudiencesRoute: typeof AudiencesRoute
  CreateRoute: typeof CreateRoute
  InventoryRoute: typeof InventoryRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SearchRoute: typeof SearchRoute
  StudioRoute: typeof StudioRoute
  TagDotjsRoute: typeof TagDotjsRoute
  WebRoute: typeof WebRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  PSlugRoute: typeof PSlugRoute
  ApiAdsClickRoute: typeof ApiAdsClickRoute
  ApiAdsOfferRoute: typeof ApiAdsOfferRoute
  ApiAdsRunRoute: typeof ApiAdsRunRoute
  ApiAdsServeRoute: typeof ApiAdsServeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiences': {
      id: '/audiences'
      path: '/audiences'
      fullPath: '/audiences'
      preLoaderRoute: typeof AudiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag.js': {
      id: '/tag.js'
      path: '/tag.js'
      fullPath: '/tag.js'
      preLoaderRoute: typeof TagDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web': {
      id: '/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/click': {
      id: '/api/ads/click'
      path: '/api/ads/click'
      fullPath: '/api/ads/click'
      preLoaderRoute: typeof ApiAdsClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/offer': {
      id: '/api/ads/offer'
      path: '/api/ads/offer'
      fullPath: '/api/ads/offer'
      preLoaderRoute: typeof ApiAdsOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/run': {
      id: '/api/ads/run'
      path: '/api/ads/run'
      fullPath: '/api/ads/run'
      preLoaderRoute: typeof ApiAdsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/serve': {
      id: '/api/ads/serve'
      path: '/api/ads/serve'
      fullPath: '/api/ads/serve'
      preLoaderRoute: typeof ApiAdsServeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudiencesRoute: AudiencesRoute,
  CreateRoute: CreateRoute,
  InventoryRoute: InventoryRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SearchRoute: SearchRoute,
  StudioRoute: StudioRoute,
  TagDotjsRoute: TagDotjsRoute,
  WebRoute: WebRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  PSlugRoute: PSlugRoute,
  ApiAdsClickRoute: ApiAdsClickRoute,
  ApiAdsOfferRoute: ApiAdsOfferRoute,
  ApiAdsRunRoute: ApiAdsRunRoute,
  ApiAdsServeRoute: ApiAdsServeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
